name: test_plugin_demo
description: A Flutter Plugin Demo.
version: 0.0.1
author: Ning<lining201702@gmail.com>
homepage: https://github.com/NingLi-iOSer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.test_plugin_demo
    pluginClass: TestPluginDemoPlugin

